remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: io/github/denis-dbm/about
description: Here you can know more about me and what I think (or did) about software, technology and, so on.
show_downloads: false
